# Generated by Django 5.2.1 on 2025-07-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_releasecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPLog',
        ),
    ]
